### ISSUE TITLE
Way to remove logs ?

### ISSUE THREAD

**Issue by dobriseb** [manics/docker-awstats#9]
Hi,

Is there a way to remove some logs for add forgotten logs ?

**Comment by manics** [comment]
Hi, this Docker image uses the default configuration provided by AWStats if it's not overwritten. We have our own private configuration file but it's specific to our workflow, so I'm afraid we can't help with your question. Since it's not specific to the Docker image I'd recommend you try and find an AWstats forum or mailing list to obtain help.

**Comment by dobriseb** [comment]
According to awstat documentation, we need to remove files awstatsXXXXXXXX.YYYYYYY.txt.
So what I deed is :
docker run -it -v awstats-db:/var/lib/awstats ubuntu /bin/bash
In this docker :
cd /var/lib/awstats
rm FilesToBeRemoved
exit
Then relaunch the logs
